#!/usr/bin/env bash
# Generate a playground FINOS OpenPGP signing key (self-signed) for local tests.
# Not for production. Private material stays under signing/gnupg/ (gitignored).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
# shellcheck source=../lib/common.sh
source "$ROOT/scripts/lib/common.sh"

NAME="${FINOS_KEY_NAME:-FINOS OSERA Playground Signing}"
EMAIL="${FINOS_KEY_EMAIL:-osera-playground-signing@finos.org}"
PASSPHRASE="${FINOS_GPG_PASSPHRASE:-osera-playground-finos}"
SIGNING_DIR="${SIGNING_DIR:-$ROOT/signing}"
GNUPGHOME="${GNUPGHOME:-$SIGNING_DIR/gnupg}"
FORCE=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --name) NAME="$2"; shift 2 ;;
    --email) EMAIL="$2"; shift 2 ;;
    --passphrase) PASSPHRASE="$2"; shift 2 ;;
    --signing-dir) SIGNING_DIR="$2"; GNUPGHOME="$SIGNING_DIR/gnupg"; shift 2 ;;
    --force) FORCE=true; shift ;;
    -h|--help)
      cat <<EOF
usage: $0 [--name NAME] [--email EMAIL] [--passphrase PASS] [--signing-dir DIR] [--force]

Creates a self-signed OpenPGP key for playground FINOS co-sign.
Exports:
  signing/finos-signing.asc   (public)
  signing/local.env           (key ids + passphrase; gitignored)
EOF
      exit 0
      ;;
    *) usage "$0 [--name NAME] [--email EMAIL] [--passphrase PASS] [--signing-dir DIR] [--force]" ;;
  esac
done

require_cmd gpg

export GNUPGHOME
mkdir -p "$GNUPGHOME" "$SIGNING_DIR"
chmod 700 "$GNUPGHOME"

pub_out="$SIGNING_DIR/finos-signing.asc"
env_out="$SIGNING_DIR/local.env"

if [[ -f "$pub_out" || -d "$GNUPGHOME" ]] && [[ "$FORCE" != true ]]; then
  echo "error: playground signing material already exists (pass --force to recreate)" >&2
  exit 1
fi
if [[ "$FORCE" == true ]]; then
  rm -rf "$GNUPGHOME"
  rm -f "$pub_out" "$env_out" "$SIGNING_DIR"/vendors/*.asc
  mkdir -p "$GNUPGHOME"
  chmod 700 "$GNUPGHOME"
fi

batch="$(mktemp "${TMPDIR:-/tmp}/osera-finos-key.XXXXXX")"
trap 'rm -f "$batch"' EXIT
cat > "$batch" <<EOF
%echo Generating FINOS playground signing key
Key-Type: RSA
Key-Length: 3072
Key-Usage: sign
Name-Real: $NAME
Name-Email: $EMAIL
Expire-Date: 1y
Passphrase: $PASSPHRASE
%commit
%echo done
EOF

gpg --batch --generate-key "$batch"
key_id="$(gpg --list-secret-keys --with-colons "$EMAIL" | awk -F: '/^sec:/ { print $5; exit }')"
key_fpr="$(gpg --list-secret-keys --with-colons "$EMAIL" | awk -F: '/^fpr:/ { print $10; exit }')"
[[ -n "$key_id" && -n "$key_fpr" ]] || {
  echo "error: failed to resolve FINOS key id for $EMAIL" >&2
  exit 1
}

gpg --armor --export "$key_fpr" > "$pub_out"

{
  echo "# Generated by generate-finos-key.sh — do not commit"
  echo "export GNUPGHOME=\"$GNUPGHOME\""
  echo "export FINOS_GPG_KEY_ID=$key_id"
  echo "export FINOS_GPG_KEY_FPR=$key_fpr"
  echo "export FINOS_GPG_PASSPHRASE=$(printf '%q' "$PASSPHRASE")"
} > "$env_out"
chmod 600 "$env_out"

echo "wrote $pub_out"
echo "wrote $env_out"
echo "FINOS_GPG_KEY_ID=$key_id"
echo "FINOS_GPG_KEY_FPR=$key_fpr"
echo "source $env_out before signing"
