name: 🤝 OSERA General Meeting Minutes
description: To track OSERA General meeting agenda and attendance
title: "MMM DD YYYY - OSERA General Meeting Minutes"
labels: ["meeting"]
body:
  - type: markdown
    attributes:
      value: |
        Time: 12.30pm ET / 5.30pm GMT
  - type: markdown
    attributes:
      value: |
        Please fill out the meeting details below.
  - type: textarea
    id: meeting_details
    attributes:
      label: Meeting Details
      description: Meeting link and registration information
      value: |
        - Meeting link: https://zoom-lfx.platform.linuxfoundation.org/meeting/95879594988?password=db0e5178-0bf3-4851-aba2-c9e480e9a58a
  - type: textarea
    id: notices
    attributes:
      label: Meeting Notices
      description: These notices will be included in the issue body
      value: |
        - The meeting host is responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/).

        - **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

        - FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

        - FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.
  - type: textarea
    id: agenda
    attributes:
      label: Agenda
      description: Meeting agenda items
      value: |
        - [ ] Convene & roll call
        - [ ] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf)
        - [ ] Review Meeting Notices (see above)
        - [ ] @mindthegab Review previous meeting actions - {link to previous meeting's issue}
        - [ ] @mindthegab - Corporate update
        - [ ] @DovOps - Remediation Standards update
        - [ ] @d1gital-f - Operations Taskforce update
        - [ ] all - CTAs
        - [ ] AOB, Q&A & Adjourn
    validations:
      required: true
  - type: textarea
    id: actions
    attributes:
      label: Action Items
      description: List action items from the meeting
      value: |
        - [ ] Action 1
        - [ ] Action 2
        - [ ] ...
